name: ElementArmour
main: org.ah.minecraft.armour.Plugin
version: 1.4.4


commands:
   ElementArmour:
      description: ElementArmour help
      usage: /ElementArmour
      permission: 
      permission-message: You don't have <permission>
   Dark:
      description: Dark
      usage: /Dark
      permission: armour.debug
      permission-message: You don't have <permission>
   Earth:
      description: Earth
      usage: /Earth
      permission: armour.debug
      permission-message: You don't have <permission>
   Metal:
      description: Metal
      usage: /Metal
      permission: armour.debug
      permission-message: You don't have <permission>
   Rain:
      description: Rain
      usage: /Rain
      permission: armour.debug
      permission-message: You don't have <permission>
   Ice:
      description: Ice
      usage: /Ice
      permission: armour.debug
      permission-message: You don't have <permission>
   Poison:
      description: Poison
      usage: /Poison
      permission: armour.debug
      permission-message: You don't have <permission>
   Lightning:
      description: Lightning
      usage: /Lightning
      permission: armour.debug
      permission-message: You don't have <permission>
   Lava:
      description: Lava
      usage: /Lava
      permission: armour.debug
      permission-message: You don't have <permission>
   Obsidian:
      description: Obsidian
      usage: /Obsidian
      permission: armour.debug
      permission-message: You don't have <permission>
   Sky:
      description: Sky
      usage: /Sky
      permission: armour.debug
      permission-message: You don't have <permission>
   Fire:
      description: Fire
      usage: /Fire
      permission: armour.debug
      permission-message: You don't have <permission>
   Air:
      description: Air
      usage: /Air
      permission: armour.debug
      permission-message: You don't have <permission>
   Water:
      description: Water
      usage: /Water
      permission: armour.debug
      permission-message: You don't have <permission>
   giveColorArmour:
      description: give Color Armour
      usage: /giveColorArmour <R> <G> <B>
      permission: armour.debug
      permission-message: You don't have <permission>
   Ninja:
      description: Ninja
      usage: /Ninja
      permission: armour.debug
      permission-message: You don't have <permission>
   Bouncer:
      description: Bouncer
      usage: /Bouncer
      permission: armour.debug
      permission-message: You don't have <permission> 
   setMonkeyHead:
      description: setMonkeyHead
      usage: /setMonkeyHead
      permission: armour.debug
      permission-message: You don't have <permission>
   Shop:
      description: Shop
      usage: /Shop
      permission: armour.debug
      permission-message: You don't have <permission>   
   sea:
      description: sea
      usage: /sea
      permission: armour.debug
      permission-message: You don't have <permission>
   spawnTower:
      description: spawnTower
      usage: /spawnTower
      permission: armour.debug
      permission-message: You don't have <permission>
   
   
      
premissions:
   armour.debug:
      description: Allows ops only to acsess these commands.
      default: op