name: GameTweaks
main: org.ah.minecraft.tweaks.TweaksCore
version: 0.1


commands:
   tweaks:
      description: tweaks
      usage: /tweaks
      permission: 
      permission-message: You don't have <permission>
   